### ISSUE TITLE
installing UI5Runner plugin interferes with execution of other run configurations

### ISSUE THREAD

**Issue by segrey** [asebak/UI5-IntelliJ-Plugin#2]
For example, debugging Node.js run configurations (contributed by NodeJS plugin) is broken sometimes when UI5Runner is also installed.

The problem is that UI5Runner (https://github.com/asebak/UI5-IntelliJ-Plugin/blob/7023ebd74120e902274be8bfde9b5d1f3d9195bd/src/Runner/UI5Runner.java) is used by IntelliJ platform when debugging Node.js run configurations, because `<programRunner implementation="Runner.UI5Runner"/>` extension point is collected before NodeJS one.

Here UI5Runner is used because its `canRun` method accepts all run configurations: https://github.com/asebak/UI5-IntelliJ-Plugin/blob/7023ebd74120e902274be8bfde9b5d1f3d9195bd/src/Runner/UI5Runner.java#L53.

To target UI5RunConfiguration instances only in run mode:
```
  public boolean canRun(@NotNull String executorId, @NotNull RunProfile profile) {
    return DefaultRunExecutor.EXECUTOR_ID.equals(executorId) && profile instanceof UI5RunConfiguration;
  }
```

**Comment by asebak** [comment]
Thanks Segrey I will look into much appreciated

**Comment by segrey** [comment]
Thank you for the prompt turnaround!
