### ISSUE TITLE
Update plugin for IntelliJ IDEA 15 and WebStorm 11

### ISSUE THREAD

**Issue by Holdo** [asebak/ui5-intellij-plugin#28]
Hello,
is it possible to use this plugin with newer versions of IntelliJ IDEA 15 and WebStorm 11? Or can you update the plugin to support them as well?

**Comment by asebak** [comment]
Just tested it out on IDEA 15 and it works fine as it is now, I assume it will work also on WebStorm 11 since its based on the same SDK.
